[project]
name = "ReceiptCheckerAPI"
version = "0.1.0"
description = ""

requires-python = ">=3.9"
readme = "README.md"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pre-commit>=4.0.0",
    "pyright>=1.1.383",
    "pytest>=8.3.3",
    "ruff>=0.6.9",
]